### ISSUE TITLE
Просит обновление

### ISSUE THREAD

**Issue by ghost** [hexlet-components/js-immutable-fs-trees#47]
Добрый день.,  установил пакет.Пробую вывести на печать .. выскакивает предупреждение с рекомендацией обновиться.
![2024-02-03_22-02-06](https://github.com/hexlet-components/js-immutable-fs-trees/assets/153673077/063e7a94-16ac-4d07-b92b-99c97f2ea327)
есть ли решение?

**Comment by fey** [comment]
@dzencot

**Comment by dzencot** [comment]
Сейчас должно работать без предупреждения
